### ISSUE TITLE
Broken link to database model documentation

### ISSUE THREAD

**Issue by arbolitoloco** [SpeciesFileGroup/taxonworks_doc#1]
[http://rdoc.taxonworks.org/frames](http://rdoc.taxonworks.org/frames) throws a 403 Forbidden error, so the link in [CONTRIBUTING.md](https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/CONTRIBUTING.md) does not work.

**Comment by mjy** [comment]
Thanks @arbolitoloco! We filled the HD on a backup last nite and the rebuild (triggered on every commit to the dev branch) wiped the help, but couldn't it couldn't be rebuilt.  Should be live now.
