### ISSUE TITLE
RDOC overwritten by subclass

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_doc#13]
Classes in Queries::Query::TaxonName are over-writing classes like ::TaxonName.

**Comment by mjy** [comment]
@LocoDelAssembly both https://www.rubydoc.info/github/SpeciesFileGroup/taxonworks and rdoc.taxonworks.org are missing a lot of core classes.  Seems like we need to focus on getting this resolved. 

We also need to get rdoc.taxonworks.org off of our servers, and/or into our kubernetes.

**Comment by LocoDelAssembly** [comment]
@mjy seems both are present.
* https://www.rubydoc.info/github/SpeciesFileGroup/taxonworks/TaxonName `TaxonName < ApplicationRecord`
* https://www.rubydoc.info/github/SpeciesFileGroup/taxonworks/Queries/TaxonName `Queries::TaxonName`

Do you have an example of missing core class?
