### ISSUE TITLE
SOP/Best practices for OTU - OTU missidentifications

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_doc#20]
Missidentifications are OTU assertions.  

As a curator I want to know how to represent historical missidentifications that have been subsequenctly cited in the literature as corrected.

How do I represent the OTU and persist the old name used, and the (non-nomenclatural) synonym?

How do I represent these data in the absence of using TaxonDeterminations on Specimens.

**Comment by proceps** [comment]
Both Nomenclature and OTU basics are updated
