### ISSUE TITLE
SOP/Best practices - representing family group name relationships

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_doc#21]
As a curator I want to represent ICZN family group names.  Describe how to:

* Create a protonym representing the form of the original family group name, as it was made available.
* Relate that original protonym to a subsequent protonym that is the current family group name.
* Relate any family-group protonym to higher taxon in "source classified as", i.e. historical context

**Comment by proceps** [comment]
nomenclature documentation is updated
