### ISSUE TITLE
Clarify soft validation triggers for original combinations of species in subgenera

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks_doc#32]
Not clarified here:
https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/manuals/NOMENCLATURE_BASICS.md

Example: 
1) Monotoma bicolor is described in 1800 in genus Monotoma. 
2) 1900 someone creates subgenus of Monotoma, Monotoma (Gyrocecis)
3) New "combination" is now Monotoma (Monotoma) bicolor. 
4) When creating prononym in TW, what names do I put in "Original Combination" fields?

Right now, only way to get soft validation (of: "Original Combination: Relationship should move from genus Monotoma to subgenus Monotoma”) to disappear is by placing the subgenus name "Monotoma" in the genus rank in Original Combination. 
Example:
![image](https://user-images.githubusercontent.com/11411328/101541429-1617b800-3967-11eb-93d1-73587b1e9c09.png)

Is this correct?

**Comment by tmcelrath** [comment]
@proceps thoughts?

**Comment by proceps** [comment]
Yes, this is correct. The best practice is to move all relationship to the lowest rank of coordinated taxon. The soft validation fix will do it automatically eventually. For display reasons, it does not matter which one you select. Soft validation message could be just ignored. Same for synonymy, all synonym relationship should be attached to the taxon of lower rank.
