### ISSUE TITLE
As a curator I want to know the SOP for generating a citation for my data in a TaxonWorks project.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_doc#40]
Related: https://github.com/SpeciesFileGroup/taxonworks/issues/1666

**Comment by tmcelrath** [comment]
Initial Question from TCM - what are your thoughts on how we can best cite the Cucujoidea World Catalog right now?We have a paper going to print soon that cites data from the catalog, but we don't have a DOI or URL to cite.
We can just use the project URL: https://sfg.taxonworks.org/projects/14. But that's password protected. Which is fine, but not super repeatable or trackable.

**Comment by mjy** [comment]
* Consider how PURLs might be used to temporarily. 
* Consider what metadata we need to record to generate list of citable projects (e.g. perhaps those with project token exposed at minimum)
* Consider SFG rewarding those who expose their data without reservation via their aid in minting DOIs

**Comment by JohnHeraty** [comment]
Similar Questions for the Universal Chalcidoidea Database.

**Authorship**:  is this still Noyes as author, or do we start citing the chalcid consortium, or our core group (Noyes, Yoder, Woolley, Burks, me; we were all at the heart of getting this up and running), or what (recognizing other curators: Dal Molin, Jansta, Dale-Skey, etc = Chalcidoidea Consortium of Curators)

**Title**: still Universal Chalcidodea Database? or TaxonWorks Chalcidoidea Database?

**Website link**: website link (alas closed to the public)?? Can we get a static version for public viewing without non 'public' pdfs?

**Comment by proceps** [comment]
I think it is good to have TaxonWorks... or TaxonWorks:... as a prefix for all project names.

**Comment by mjy** [comment]
There is not going to be an easy answer here, and almost certainly there will be multiple answers.

Things to remember: 
* There is no one Taxonworks!
* SFG has historical reason to keep "Species Files" as the names of some projects.
* Referencing TaxonWorks only makes sense if the product being cited is accessible to the person reading the citation *in* TaxonWorks.  See below. 
* No projects are accessible to all except through the API.  Therefor a citation to a TaxonWorks dataset should reference the API, at least for the time being?
* Remember what a citation is for, it's for the user to be able to get to the core matter.  You don't site what you can't get to (though, I suppose, this is violated every day when we reference literature behind paywalls...  hmm).

I think perhaps focus on the types of citations we want to make, I suspect this will help guide things:
* Access to real-time data
* Access to a complete snapshot in time
* Access to a partial/slice in time

... others?

**Comment by mjy** [comment]
Revised types of citations to consider:

* Software
  * Access to the source code
* Data (a citation means you are granting others access to this resource)
   * All the data
     * The data as rendered in a public facing website
     * In real time (TW API)
     * A snapshot (SQL dump to Zenodo)
     * The whole thing, behind a "playwall" (e.g. current citations practices)  
   * A slice of the data
      * In real time
        * Specific TW API query referencing the API version
        *  URL to TW Download accessible in the API 
      * A file dump of some sort… on Zenodo etc.

**Comment by debpaul** [comment]
Citing Specify Software (from [a recent paper in BDJ](https://doi.org/10.3897/BDJ.8.e55959)).

**in the text**
![image](https://user-images.githubusercontent.com/2990155/116160794-4b276b80-a6b8-11eb-9179-1fded03fd508.png)
Note the first URL points to this text:
> Specify Collections Consortium (2019) Specify 6. 6.7.04. University of Kansas Center for Research. Release date: 2019-10-15. URL: https://www.sustain.specifysoftware.org/

the second URL in the above screenshot points to:
> Specify Collections Consortium (2017) Biological collections using Specify. http://www.sustain.specifysoftware.org/wp-content/uploads/2017/10/Specify-Collections-9-18-17.pdf. Accessed on: 2019-6-04.

**in the references**
![image](https://user-images.githubusercontent.com/2990155/116161155-e587af00-a6b8-11eb-8753-1bba9ae3d5d7.png)

@mjy which of your examples outlined above do these fit as exemplar? While https://www.sustain.specifysoftware.org takes you to the project pages, you then do have to go and find the spot to download their various versions of code available.

In the article, (from a very quick read), I don't see anywhere that the authors specifically stated which version of specify they are using ...

**Comment by debpaul** [comment]
Some [Bibtext examples](https://verbosus.com/bibtex-style-examples.html)

**Comment by debpaul** [comment]
Note Voyant tools has an interesting Cite Me tool we can look at. 
![image](https://user-images.githubusercontent.com/2990155/119572468-66010480-bd78-11eb-8abb-bde32b9fe735.png)

**Comment by mjy** [comment]
![Screen Shot 2021-05-25 at 4 50 02 PM](https://user-images.githubusercontent.com/22600/119573156-81204400-bd79-11eb-8397-57dc6e83eade.png)

![Screen Shot 2021-05-25 at 4 50 14 PM](https://user-images.githubusercontent.com/22600/119573213-91382380-bd79-11eb-9d52-670f68d630a6.png)

![Screen Shot 2021-05-25 at 4 50 20 PM](https://user-images.githubusercontent.com/22600/119573231-97c69b00-bd79-11eb-8302-07073e34e666.png)

**Comment by JohnHeraty** [comment]
The formatted version in TW is pretty odd (Group, S.F.) and the same in endnotes.

The best I can do in endnotes is:
Species_File_Group and Collaborators. (2021) Taxonworks, software by the Taxonworks Collaborative Community. [Available via https://taxonworks.org <https://taxonworks.org/>].

so what about the TW Universal Chalcidoidea Database?

**Comment by debpaul** [comment]
Interesting note (although it doesn't seem to work), I found a reference that suggests if you put the value for the element (in bibtex) in quotation marks, that BibTeX would display an organization name correctly.

See [How can I make an organization name display correctly?](https://clemson.libguides.com/LaTeX#7)

>BibTeX reads text in the author field as an author's name or names unless told otherwise. For example, say a reference exported from RefWorks contains the line:
    author={Institute of Electrical Engineers},
BibTeX will read this field as a person's name, where the first name is "Institute" and the last name is "of Electrical Engineers," and would format accordingly. Use a text editor and to add quotes around the field so that the line reads:
    author="{Institute of Electrical Engineers}",
Now BibTeX will read this all as one piece rather than as a person's name, and will format correctly.

**Comment by debpaul** [comment]
See https://www.force11.org/software-citation-principles

**Comment by debpaul** [comment]
Trying to use double {{author string}} or {\{author string}}  as suggested to preserve literal text string for author.
So far, no joy. 
See https://tex.stackexchange.com/questions/10808/using-a-corporate-author-in-the-author-field-of-a-bibliographic-entry-spell
for what some say works.
