### ISSUE TITLE
As a curator, I want a list of fields that TW understands for DwC/batch specimen imports.

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks_doc#43]
Now that direct naming of TW fields inside DwC tsv imports is possible (eg TW::CollectionObject::BufferedDeterminations), it would be very helpful to have a complete list of the available TW fields.

This would allow me to cut out the DwC middleman and map our native db column names directly to TW ones.

Not all DwC fields have mappings in TW, and so making my data DwC compliant does not necessarily mean it's in the best format for TW.

Also, the identification/namespace fields are not well documented in how they map to TW, but maybe that's just me.

| DwC field        | TW Field                |
|------------------|-------------------------|
| institutionCode  | repository              |
| collectionCode   | local namespace         |

**Comment by LocoDelAssembly** [comment]
>Now that direct naming of TW fields inside DwC tsv imports is possible (eg TW::CollectionObject::BufferedDeterminations), it would be very helpful to have a complete list of the available TW fields.

@LordFlashmeow these are the fields currently opened for direct manipulation outside DwC standard:

|TW::CollectionObject::*|
|---|
|buffered_collecting_event|
|buffered_determinations|
|buffered_other_labels|
|total|

|TW::CollectingEvent::*|
|---|
|document_label|
|print_label|
|verbatim_label|
|field_notes|
|formation|
|group|
|lithology|
|max_ma|
|maximum_elevation|
|member|
|min_ma|
|minimum_elevation|
|elevation_precision|
|start_date_day|
|start_date_month|
|start_date_year|
|end_date_day|
|end_date_month|
|end_date_year|
|time_end_hour|
|time_end_minute|
|time_end_second|
|time_start_hour|
|time_start_minute|
|time_start_second|
|verbatim_collectors|
|verbatim_date|
|verbatim_datum|
|verbatim_elevation|
|verbatim_geolocation_uncertainty|
|verbatim_habitat|
|verbatim_latitude|
|verbatim_locality|
|verbatim_longitude|
|verbatim_method|
|verbatim_trip_identifier|

> Also, the identification/namespace fields are not well documented in how they map to TW, but maybe that's just me.

`institutionCode` maps to maps to existing `Repository` instance matched by acronym and assigns it to the collection object. Then *the value* of the institutionCode:collectionCode pair is used to look up the namespace you configured in settings to be used for the identifier created from `catalogNumber`. `collectionCode` itself is not imported.

**Comment by LordFlashmeow** [comment]
Good to know those are the available fields. Did you pull them from the `accepted_attributes` lists in occurrence.rb or somewhere else? Might be handy to include them in a guide/manual for batch importing (when it gets written).
