### ISSUE TITLE
503 Service Unavailable, URL doesn't resolve from Developers.md page

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks_doc#44]
From Developers > Documentation > Code
https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/DEVELOPERS.md#code
>This doc is also generated at https://rdoc.info/github/SpeciesFileGroup/taxonworks.

this url https://rdoc.info/github/SpeciesFileGroup/taxonworks is not found or I get a 503
![image](https://user-images.githubusercontent.com/2990155/128078879-ba719c27-80ca-4461-bc81-3ac898e16cdd.png)
OR I See This

![image](https://user-images.githubusercontent.com/2990155/128079095-1190ac6b-f067-45c0-9ba6-dc75354b3176.png)

**Comment by LocoDelAssembly** [comment]
Yes, rdoc.info hasn't been working for us for quite some time. Looks it will never come back so it is best to no longer mention in.
