### ISSUE TITLE
Vue Files in TW docs/concepts not openable in Vue Software

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks_doc#45]
Problem: VUE files not viewable.
These [Vue files](https://github.com/SpeciesFileGroup/taxonworks_doc/tree/master/concepts)

Actions:

- Installed latest Vue software for Windows and launched it.
- Pointed to URL: https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/concepts/TaxonConceptRelationships.vue to open it
- Got ERR MSG: **Map can't be opened in current version of Vue software.**
- and this popup

![image](https://user-images.githubusercontent.com/2990155/128083852-eb02d38d-e884-48ed-98c5-98326c710f98.png)

**Solution:** I don't know. Is there a way to update these Vue files @mjy?

**Comment by debpaul** [comment]
Hm. Maybe it's because Java is required? Although I do have it installed (for OpenRefine). I wonder if it's a version issue.

**Comment by mjy** [comment]
You need to point to the raw file, not the web-page: `https://raw.githubusercontent.com/SpeciesFileGroup/taxonworks_doc/master/concepts/TaxonConceptRelationships.vue`. This may/not solve it.

**Comment by mjy** [comment]
Closing, re-open if above doesn't work.
