### ISSUE TITLE
Table structure

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks_doc#7]
I am trying to understand the taxonworks underlying concepts. While the scope is more or less clear, I miss documentation about data model and table structure,  as available for speciesfile [http://help.speciesfile.org/index.php/List_of_tables](http://help.speciesfile.org/index.php/List_of_tables)
Maybe I missed something? Or is this software working without tables?

**Comment by mjy** [comment]
Thankes for pushing this forward @klausriede. I'll expand this further here, but a couple of short points:

* The schema is updated from time to time here [https://github.com/SpeciesFileGroup/taxonworks/blob/development/db/schema.rb](https://github.com/SpeciesFileGroup/taxonworks/blob/development/db/schema.rb).  Note that this might be a) out of date, and b) may not represent all changes on all branches.  
* You can see the evolution of the whole schema in the database migrations under `/db/migrations`
* The easiest way to to get an over view, however, is the interface itself, every card in in the 'Data' tab on the hub represents a single table, this is more or less the complete schema for data.
* For a card in 'Data' view the corresponding Rdoc model at http://rdoc.taxonworks.org
* Some conceptual bits (only a tiny bit) are slowly being added here https://github.com/SpeciesFileGroup/taxonworks_doc/tree/master/concepts
* Technical specification will ultimately come at taxonworks_api website

**Comment by klausriede** [comment]
Thanks for this, I will look into all this!

**Comment by mjy** [comment]
Table descriptions, and more are available here: https://docs.taxonworks.org/develop/Data/tables.html
